#########################################################################################################################  
#  This is a compose.yml file to deploy a multi-container application using WordPress and MariaDB as database backend ###
#  Compose file also creates two networks, one for Frontend app and second to connect between two containers          ###
########################################################################################################################                
services:
  frontend:
    image: quay.io/dbais76/wordpress:1.0
    container_name: frontend  
    ports:
      8080:80
    restarts:
      always
    networks:
      - user-nw
      - db-net  
    environment:
      - WORDPRESS_DB_HOST=backend
      - WORDPRESS_DB_USER=demouser
      - WORDPRESS_DB_PASSWORD=demopass
      - WORDPRESS_DB_NAME=demodb
    depends_on:  ## defines that frontend container needs backend container up and running and in a way, defines the order
      - backend    
  backend:
    image: quay.io/dbais76/mariadb:10.6.4
    command: '--default-authentication-plugin=mysql_native_password'
    container_name: backend  
    volumes:
      - db-vol:/var/lib/mysql
    networks:
      - db-net
    restarts:
      always
    environment:
      - MYSQL_USER=demouser
      - MYSQL_PASSWORD=demopass
      - MYSQL_ROOT_PASSWORD=I@mGr00T
      - MYSQL_DATABASE=demodb
    expose:
      - 3306
      - 13306
volumes:
  db-vol: {}
networks:
  user-nw: {}
  db-net: {}  
